###
GET http://localhost:3000/ciclo/listar

###
GET http://localhost:3000/ciclo/listar/123456789/98745

###
POST http://localhost:3000/ciclo/cadastrar
Content-Type: application/json

{
    "data": "2021/04/08" ,
    "creditos":[{
        "nome": "teste",
        "valor": 123
    }],
    "debitos":[{
        "nome": "teste",
        "valor": 123,
        "status": "PAGO"
    }]
}